name: TVTComment build and release

on:
  push:
    tags:
      - 'v*'
  
jobs:
  exe-build:
    name: TVTComment.exe build
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build (TVTComment.exe)
        run: dotnet publish -c Release /p:PublishProfile="TVTComment/Properties/PublishProfiles/ReleaseProfile.pubxml"

      - name: Copy asset (TVTComment.exe)
        shell: powershell
        run: |
          New-Item -Path Asset -ItemType Directory
          New-Item -Path Asset/misc -ItemType Directory
          Copy-Item -Path TVTComment/bin/Release/net5.0-windows/publish/TvtComment.exe -Destination Asset/
          Copy-Item -Path TVTComment/Data/* -Destination Asset/
          Copy-Item -Path CHANGELOG.md -Destination Asset/misc/CHANGELOG.txt
          Copy-Item -Path LICENSE -Destination Asset/misc/LICENSE.txt
          Copy-Item -Path README.md -Destination "Asset/misc/README edit noriokun4649.txt"
        
      - name: Upload asset to Artifacts (TVTComment.exe)
        uses: actions/upload-artifact@v2
        with:
          name: TvtComment
          if-no-files-found: error
          path: Asset/
          
  tvtp-build:
    name: tvtcomment.tvtp build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x64
          - Win32
          
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build (tvtcomment.tvtp)
        run: msbuild NicoJK/NicoJK.vcxproj /p:Configuration="Release" /p:Platform="${{ matrix.platform }}" /p:CodePage=932
        
      - name: Copy asset (tvtcomment.tvtp)
        shell: powershell
        run: |
          New-Item -Path Asset -ItemType Directory
          Copy-Item -Path NicoJK/${{ matrix.platform }}/Release/TvtComment.tvtp -Destination Asset/
                
      - name: Upload asset to Artifacts (tvtcomment.tvtp)
        uses: actions/upload-artifact@v2
        with:
          name: TvtComment_${{ matrix.platform }}
          if-no-files-found: error
          path: Asset/

  release:
    needs: 
      - exe-build
      - tvtp-build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: Asset/
      
      - name: Get version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
        
      - name: Move misc files
        run: |
          mv Asset/TvtComment/misc/* Asset/ 
          rmdir Asset/TvtComment/misc
        
      - name: Repack assets
        run: |
          cd Asset
          7z a -r ../TvtComment_v${{ env.RELEASE_VERSION }}.zip *

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TvtComment_v${{ env.RELEASE_VERSION }}.zip
          asset_name: TvtComment_v${{ env.RELEASE_VERSION }}.zip
          asset_content_type: application/zip
      
